---
title: "Homework-2"
author: "Tianqi Zhao"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Ridge regression function
```{r}
ridge_reg <- function(formula, lambda,data){
  m <- model.matrix(formula, data)
  yname <- formula[[2]]
  y <- as.matrix(data[paste0(yname)])
  
  # use svd to calculate the estimated beta
  svd_obj <- svd(m)
  beta <- svd_obj$v %*% diag(svd_obj$d/((svd_obj$d)^2 + lambda)) %*% t(svd_obj$u) %*% y
  rownames(beta) <- colnames(m)
  ret <- list(coefficients = beta, lambda = lambda)
  
  # change the class to ridge_reg
  class(ret) <- "ridge_reg"
  ret
}
```

```{r, echo = FALSE}
library(bis557)
data(ridge_train)
data(ridge_test)
```

# Change in out-of-sample MSE as lambda varies
```{r}
lambda <- log(seq(1, 20000, 0.1))
formula <- y ~. -1
ridge_mse <- function(formula, lambda, ridge_test) {
  y_predict <- as.matrix(ridge_test[,-1]) %*% as.matrix(ridge_reg(formula, lambda, ridge_train)$coefficients)
  mse <- mean((y_predict - ridge_test[,1])^2)
  mse
}

mse_result <- matrix(NA, length(lambda))
for (i in 1:length(lambda)) {
  mse_result[i,] <- ridge_mse(formula, lambda[i], ridge_test)
}

plot(lambda, mse_result, type = 'l', xlab = "log(lambda)", ylab = "MSE of Test Set")

lambda[which.min(mse_result)]
```

As can be seen from the plot, the out-of-sample MSE decreases when log(lambda) increases. 